version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 8088:80
    volumes:
      - ./src/:/srv/app
  php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    ports:
      - 9001:9000
    volumes:
      - ./src/:/srv/app
